version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: rpi-rfid-postgres
    environment:
      POSTGRES_DB: rpi-rfid-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rpi-rfid-network
    restart: always

volumes:
  postgres-data:

networks:
  db-network:

